apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: easyshop
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://108.130.42.240/api"
  NEXTAUTH_URL: "https://108.130.42.240"
  NEXTAUTH_SECRET: "jYcM06dt07LhGJ5QHuYbvZuMHEeHV1Ivfr/pch78nJE="
  JWT_SECRET: "285fe5e988f75fac82ce48eef9a5aac2bc0f49d25646a80a3ccf731078ca967i"
